### ISSUE TITLE
Light level control

### ISSUE THREAD

**Issue by gsainsbury86** [marconicivitavecchia/unifi-led-api#2]
Hi,

I'm thinking about getting some of these panels to act as a psuedo skylight for my home office. I'd like to be able to use the unofficial REST API to be able to control the light level in response to the light level outside.

I was wondering if you know if:
1. Do these commands that you've documented still work with the current firmware?
2. Does the PUT `{"command":"config-output","value":0}` command accept a float in the range 0-1?

Thanks!

**Comment by wbigger** [comment]
Hi George! Thank you for your interest.

It is a while that we don't use these API and unfortunately I can't answer to you right now (we are using only the official control dashboard recently). If you are not in a hurry, I can try to make some test in the next days.

Let me know if it can help you.

**Comment by gsainsbury86** [comment]
Thanks @wbigger , I'd really appreciate you testing if you had the time!

I really would like to be able to automate the lights if possible. I can't really see what the controls within the app would allow without actually owning any of the panels yet. Do you know if you can schedule on/offs and dimming?

**Comment by wbigger** [comment]
We used NodeRED to connect panels with almost everything. Beyond triggering
REST API by time and date, we used it to control lights with a Telegram bot.

**Comment by gsainsbury86** [comment]
Great, thanks! I'll go ahead and order one and see how I go! Appreciate your time.

**Comment by gsainsbury86** [comment]
Thanks again @wbigger . My panel arrived today and I was able to use your Postman setup to control the light levels. Now I'll be able to script it up to follow the external light levels as I'd hoped!

**Comment by wbigger** [comment]
Great! I'm very happy to have been of help 👌
